### PR TITLE
Updated connectController so array can be used as route controllers

### PR DESCRIPTION
**Pull request by magnuspaaske**
What the title says. I updated the connectController so that route controllers can now either be functions or arrays of functions. This way multiple middleware functions can be strung together to handle a route, making code reuse easier.

### CODE REVIEW

**Review by davesag — CHANGES_REQUESTED** [review]
I like it.  Would you mind also updating the README file so other know they can use arrays of functions now too.  Also feel free to add yourself to the `contributors` section of `package.json`

**Comment by davesag** [comment]
@magnuspaaske I've got another PR open to upgrade the package-lock file to suit the new NPM format.  I won't merge that until you are done however.

**Review by davesag — APPROVED** [review]

**Comment by davesag** [comment]
I've decided to update the docs myself.  Your change has some interesting applications for applying middleware independently of the swagger definition file, which is a plus in some cases.

**Comment by davesag** [comment]
@magnuspaaske your changes have been included in release 3.3.0.  Thanks again for your input. Your change is very beneficial.

**Comment by magnuspaaske** [comment]
This is awesome. Looking forward to using it in production :)

**Pull request merged**
